#  Copyright (c) 2017-2018 Uber Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Minimal example of how to read samples from a dataset generated by `hello_world_dataset.py`
using pytorch"""

from __future__ import print_function

from pyspark.sql import SparkSession

from examples.hello_world.hello_world_dataset import HelloWorldSchema
from petastorm.spark_utils import dataset_as_rdd


def pyspark_hello_world(dataset_url='file:///tmp/hello_world_dataset'):
    spark = SparkSession \
        .builder \
        .master('local[1]') \
        .getOrCreate()

    # dataset_as_rdd creates an rdd of named tuples.
    rdd = dataset_as_rdd(dataset_url, spark,
                         [HelloWorldSchema.image1, HelloWorldSchema.id])
    print(rdd.first().id)


if __name__ == '__main__':
    pyspark_hello_world()
